#!/bin/bash
 
CONF_DIR=/home/deploy/shuteye.co
CONF_FILE=shuteye.god
GOD_BIN=/usr/local/bin/god
RUBY_BIN=/usr/bin/ruby
RETVAL=0
 
# Go no further if config directory is missing.
[ -d "$CONF_DIR" ] || exit 0
 
case "$1" in
    start)
      # Create pid directory
      $RUBY_BIN $GOD_BIN -c $CONF_DIR/$CONF_FILE
      RETVAL=$?
  ;;
    stop)
      $RUBY_BIN $GOD_BIN terminate
      RETVAL=$?
  ;;
    restart)
      $RUBY_BIN $GOD_BIN terminate
      $RUBY_BIN $GOD_BIN -c $CONF_DIR/$CONF_FILE
      RETVAL=$?
  ;;
    status)
      $RUBY_BIN $GOD_BIN status
      RETVAL=$?
  ;;
    *)
      echo "Usage: shuteye {start|stop|restart|status}"
      exit 1
  ;;
esac
 
exit $RETVAL